name: 'Atatus Application Deployment Marker'
author: 'Atatus'
description: 'Apply a Atatus application deployment marker to an application that is monitored by Atatus.'
inputs:
  apiKey:
    description: 'Your Atatus API Key.'
    required: true
  projectId:
    description: 'Your Atatus project id'
    required: true
  revision:
    description: 'Commit for the deployment.'
    required: true
  releaseStage:
    description: 'The release stage (e.g., production, staging).'
    required: true
    default: 'production'
  changes:
    description: 'Change log string stored with the deployment.'
    required: true
    default: 'No Changes'
  apiUrl:
    description: 'The URL of the API to call.'
    required: false
    default: 'https://api.atatus.com/v2/projects'
outputs:
  response:
    description: 'The response from the external API call.'

runs:
  using: 'node20'
  main: 'dist/index.js'
